config/routes.rb
Agenda::Application.routes.draw do
  resources :sessions

  resources :datos_significativos

  resources :tratamiento_previos

  resources :cita

  resources :contactos

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

end

app/models/datos_significativo.rb
class DatosSignificativo < ActiveRecord::Base
  attr_accessible :accidentes, :asalto, :cambio_residencia, :carcel, :divorcio, :embarazo, :enfermedades, :matricula, :muertes, :otros, :perdida_de_empleo, :problemas_economicos, :problemas_escolares, :problemas_genericos, :secuestro, :separacion
end

app/controllers/datos_significativos_controller.rb
class DatosSignificativosController < ApplicationController
  # GET /datos_significativos
  # GET /datos_significativos.json
  def index
    @datos_significativos = DatosSignificativo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datos_significativos }
    end
  end

  # GET /datos_significativos/1
  # GET /datos_significativos/1.json
  def show
    @datos_significativo = DatosSignificativo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datos_significativo }
    end
  end

  # GET /datos_significativos/new
  # GET /datos_significativos/new.json
  def new
    @datos_significativo = DatosSignificativo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datos_significativo }
    end
  end

  # GET /datos_significativos/1/edit
  def edit
    @datos_significativo = DatosSignificativo.find(params[:id])
  end

  # POST /datos_significativos
  # POST /datos_significativos.json
  def create
    @datos_significativo = DatosSignificativo.new(params[:datos_significativo])

    respond_to do |format|
      if @datos_significativo.save
        format.html { redirect_to @datos_significativo, notice: 'Datos significativo was successfully created.' }
        format.json { render json: @datos_significativo, status: :created, location: @datos_significativo }
      else
        format.html { render action: "new" }
        format.json { render json: @datos_significativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datos_significativos/1
  # PUT /datos_significativos/1.json
  def update
    @datos_significativo = DatosSignificativo.find(params[:id])

    respond_to do |format|
      if @datos_significativo.update_attributes(params[:datos_significativo])
        format.html { redirect_to @datos_significativo, notice: 'Datos significativo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datos_significativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_significativos/1
  # DELETE /datos_significativos/1.json
  def destroy
    @datos_significativo = DatosSignificativo.find(params[:id])
    @datos_significativo.destroy

    respond_to do |format|
      format.html { redirect_to datos_significativos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/datos_significativos_helper.rb
module DatosSignificativosHelper
end

app/views/datos_significativos/_form.html.erb
<%= form_for(@datos_significativo) do |f| %>
  <% if @datos_significativo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datos_significativo.errors.count, "error") %> prohibited this datos_significativo from being saved:</h2>

      <ul>
      <% @datos_significativo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %>
    <%= f.number_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :cambio_residencia %><br />
    <%= f.text_field :cambio_residencia %>
  </div>
  <div class="field">
    <%= f.label :accidentes %><br />
    <%= f.text_field :accidentes %>
  </div>
  <div class="field">
    <%= f.label :muertes %><br />
    <%= f.text_field :muertes %>
  </div>
  <div class="field">
    <%= f.label :separacion %><br />
    <%= f.text_field :separacion %>
  </div>
  <div class="field">
    <%= f.label :divorcio %><br />
    <%= f.text_field :divorcio %>
  </div>
  <div class="field">
    <%= f.label :problemas_escolares %><br />
    <%= f.text_field :problemas_escolares %>
  </div>
  <div class="field">
    <%= f.label :perdida_de_empleo %><br />
    <%= f.text_field :perdida_de_empleo %>
  </div>
  <div class="field">
    <%= f.label :enfermedades %><br />
    <%= f.text_field :enfermedades %>
  </div>
  <div class="field">
    <%= f.label :problemas_economicos %><br />
    <%= f.text_field :problemas_economicos %>
  </div>
  <div class="field">
    <%= f.label :asalto %><br />
    <%= f.text_field :asalto %>
  </div>
  <div class="field">
    <%= f.label :secuestro %><br />
    <%= f.text_field :secuestro %>
  </div>
  <div class="field">
    <%= f.label :carcel %><br />
    <%= f.text_field :carcel %>
  </div>
  <div class="field">
    <%= f.label :problemas_genericos %><br />
    <%= f.text_field :problemas_genericos %>
  </div>
  <div class="field">
    <%= f.label :embarazo %><br />
    <%= f.text_field :embarazo %>
  </div>
  <div class="field">
    <%= f.label :otros %><br />
    <%= f.text_field :otros %>
  </div>
  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

app/views/datos_significativos/edit.html.erb
<h1>Editar Datos significativos recientes</h1>

<%= render 'form' %>

<%= link_to 'Show', @datos_significativo %> |
<%= link_to 'Back', datos_significativos_path %>

app/views/datos_significativos/index.html.erb
<h1>Lista de los Datos significativos recientes</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Cambio residencia</th>
    <th>Accidentes</th>
    <th>Muertes</th>
    <th>Separacion</th>
    <th>Divorcio</th>
    <th>Problemas escolares</th>
    <th>Perdida de empleo</th>
    <th>Enfermedades</th>
    <th>Problemas economicos</th>
    <th>Asalto</th>
    <th>Secuestro</th>
    <th>Carcel</th>
    <th>Problemas genericos</th>
    <th>Embarazo</th>
    <th>Otros</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @datos_significativos.each do |datos_significativo| %>
  <tr>
    <td><%= datos_significativo.matricula %></td>
    <td><%= datos_significativo.cambio_residencia %></td>
    <td><%= datos_significativo.accidentes %></td>
    <td><%= datos_significativo.muertes %></td>
    <td><%= datos_significativo.separacion %></td>
    <td><%= datos_significativo.divorcio %></td>
    <td><%= datos_significativo.problemas_escolares %></td>
    <td><%= datos_significativo.perdida_de_empleo %></td>
    <td><%= datos_significativo.enfermedades %></td>
    <td><%= datos_significativo.problemas_economicos %></td>
    <td><%= datos_significativo.asalto %></td>
    <td><%= datos_significativo.secuestro %></td>
    <td><%= datos_significativo.carcel %></td>
    <td><%= datos_significativo.problemas_genericos %></td>
    <td><%= datos_significativo.embarazo %></td>
    <td><%= datos_significativo.otros %></td>
    <td><%= link_to 'Show', datos_significativo %></td>
    <td><%= link_to 'Edit', edit_datos_significativo_path(datos_significativo) %></td>
    <td><%= link_to 'Destroy', datos_significativo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Datos significativo', new_datos_significativo_path %>

app/views/datos_significativos/new.html.erb
<h1>Lista de los Datos significativos recientes</h1>

<%= render 'form' %>

<%= link_to 'Back', datos_significativos_path %>

app/views/datos_significativos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @datos_significativo.matricula %>
</p>

<p>
  <b>Cambio residencia:</b>
  <%= @datos_significativo.cambio_residencia %>
</p>

<p>
  <b>Accidentes:</b>
  <%= @datos_significativo.accidentes %>
</p>

<p>
  <b>Muertes:</b>
  <%= @datos_significativo.muertes %>
</p>

<p>
  <b>Separacion:</b>
  <%= @datos_significativo.separacion %>
</p>

<p>
  <b>Divorcio:</b>
  <%= @datos_significativo.divorcio %>
</p>

<p>
  <b>Problemas escolares:</b>
  <%= @datos_significativo.problemas_escolares %>
</p>

<p>
  <b>Perdida de empleo:</b>
  <%= @datos_significativo.perdida_de_empleo %>
</p>

<p>
  <b>Enfermedades:</b>
  <%= @datos_significativo.enfermedades %>
</p>

<p>
  <b>Problemas economicos:</b>
  <%= @datos_significativo.problemas_economicos %>
</p>

<p>
  <b>Asalto:</b>
  <%= @datos_significativo.asalto %>
</p>

<p>
  <b>Secuestro:</b>
  <%= @datos_significativo.secuestro %>
</p>

<p>
  <b>Carcel:</b>
  <%= @datos_significativo.carcel %>
</p>

<p>
  <b>Problemas genericos:</b>
  <%= @datos_significativo.problemas_genericos %>
</p>

<p>
  <b>Embarazo:</b>
  <%= @datos_significativo.embarazo %>
</p>

<p>
  <b>Otros:</b>
  <%= @datos_significativo.otros %>
</p>


<%= link_to 'Edit', edit_datos_significativo_path(@datos_significativo) %> |
<%= link_to 'Back', datos_significativos_path %>