config/routes.rb
Agenda::Application.routes.draw do
  resources :sessions

  resources :datos_significativos

  resources :tratamiento_previos

  resources :cita

  resources :contactos

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

end

app/models/tratamiento_previo.rb
class TratamientoPrevio < ActiveRecord::Base
  attr_accessible :circunstancias_consultas, :internamiento, :matricula, :medicacion, :motivo, :otros_servicios, :psicoterapia
end

app/controllers/tratamiento_previos_controller.rb
class TratamientoPreviosController < ApplicationController
  # GET /tratamiento_previos
  # GET /tratamiento_previos.json
  def index
    @tratamiento_previos = TratamientoPrevio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tratamiento_previos }
    end
  end

  # GET /tratamiento_previos/1
  # GET /tratamiento_previos/1.json
  def show
    @tratamiento_previo = TratamientoPrevio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tratamiento_previo }
    end
  end

  # GET /tratamiento_previos/new
  # GET /tratamiento_previos/new.json
  def new
    @tratamiento_previo = TratamientoPrevio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tratamiento_previo }
    end
  end

  # GET /tratamiento_previos/1/edit
  def edit
    @tratamiento_previo = TratamientoPrevio.find(params[:id])
  end

  # POST /tratamiento_previos
  # POST /tratamiento_previos.json
  def create
    @tratamiento_previo = TratamientoPrevio.new(params[:tratamiento_previo])

    respond_to do |format|
      if @tratamiento_previo.save
        format.html { redirect_to @tratamiento_previo, notice: 'Tratamiento previo was successfully created.' }
        format.json { render json: @tratamiento_previo, status: :created, location: @tratamiento_previo }
      else
        format.html { render action: "new" }
        format.json { render json: @tratamiento_previo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tratamiento_previos/1
  # PUT /tratamiento_previos/1.json
  def update
    @tratamiento_previo = TratamientoPrevio.find(params[:id])

    respond_to do |format|
      if @tratamiento_previo.update_attributes(params[:tratamiento_previo])
        format.html { redirect_to @tratamiento_previo, notice: 'Tratamiento previo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tratamiento_previo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tratamiento_previos/1
  # DELETE /tratamiento_previos/1.json
  def destroy
    @tratamiento_previo = TratamientoPrevio.find(params[:id])
    @tratamiento_previo.destroy

    respond_to do |format|
      format.html { redirect_to tratamiento_previos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tratamiento_previos_helper.rb
module TratamientoPreviosHelper
end

app/views/tratamiento_previos/_form.html.erb
<%= form_for(@tratamiento_previo) do |f| %>
  <% if @tratamiento_previo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tratamiento_previo.errors.count, "error") %> prohibited this tratamiento_previo from being saved:</h2>

      <ul>
      <% @tratamiento_previo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br />
    <%= f.text_field :matricula %>
  </div>

  <div class="field">
    <% psicoterapia = {
            'Psicoterapia Individual' => 'Psicoterapia Individual',
            'De grupo' => 'De grupo',
            'Familiar' => 'Familiar',
            'De pareja' => 'De pareja',

    } %>
    <%= f.label :psicoterapia %> <br/>
    <%= f.select :psicoterapia, psicoterapia %>
  </div>



  <div class="field">
    <%= f.label :motivo %><br />
    <%= f.text_field :motivo %>
  </div>
  <div class="field">
    <%= f.label :medicacion %><br />
    <%= f.text_field :medicacion %>
  </div>
  <div class="field">
    <%= f.label :internamiento %><br />
    <%= f.text_field :internamiento %>
  </div>
  <div class="field">
    <%= f.label :otros_servicios %><br />
    <%= f.text_field :otros_servicios %>
  </div>
  <div class="field">
    <%= f.label :circunstancias_consultas %><br />
    <%= f.text_field :circunstancias_consultas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tratamiento_previos/edit.html.erb
<h1>Editing tratamiento_previo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tratamiento_previo %> |
<%= link_to 'Back', tratamiento_previos_path %>

app/views/tratamiento_previos/index.html.erb
<h1>Listing tratamiento_previos</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Psicoterapia</th>
    <th>Motivo</th>
    <th>Medicacion</th>
    <th>Internamiento</th>
    <th>Otros servicios</th>
    <th>Circunstancias consultas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tratamiento_previos.each do |tratamiento_previo| %>
  <tr>
    <td><%= tratamiento_previo.matricula %></td>
    <td><%= tratamiento_previo.psicoterapia %></td>
    <td><%= tratamiento_previo.motivo %></td>
    <td><%= tratamiento_previo.medicacion %></td>
    <td><%= tratamiento_previo.internamiento %></td>
    <td><%= tratamiento_previo.otros_servicios %></td>
    <td><%= tratamiento_previo.circunstancias_consultas %></td>
    <td><%= link_to 'Show', tratamiento_previo %></td>
    <td><%= link_to 'Edit', edit_tratamiento_previo_path(tratamiento_previo) %></td>
    <td><%= link_to 'Destroy', tratamiento_previo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tratamiento previo', new_tratamiento_previo_path %>

app/views/tratamiento_previos/new.html.erb
<h1>New tratamiento_previo</h1>

<%= render 'form' %>

<%= link_to 'Back', tratamiento_previos_path %>

app/views/tratamiento_previos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @tratamiento_previo.matricula %>
</p>

<p>
  <b>Psicoterapia:</b>
  <%= @tratamiento_previo.psicoterapia %>
</p>

<p>
  <b>Motivo:</b>
  <%= @tratamiento_previo.motivo %>
</p>

<p>
  <b>Medicacion:</b>
  <%= @tratamiento_previo.medicacion %>
</p>

<p>
  <b>Internamiento:</b>
  <%= @tratamiento_previo.internamiento %>
</p>

<p>
  <b>Otros servicios:</b>
  <%= @tratamiento_previo.otros_servicios %>
</p>

<p>
  <b>Circunstancias consultas:</b>
  <%= @tratamiento_previo.circunstancias_consultas %>
</p>


<%= link_to 'Edit', edit_tratamiento_previo_path(@tratamiento_previo) %> |
<%= link_to 'Back', tratamiento_previos_path %>