config/routes.rb
Agenda::Application.routes.draw do
  resources :sessions

  resources :datos_significativos

  resources :tratamiento_previos

  resources :cita

  resources :contactos

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :Edo_Civil, :ciudad, :colonia, :domicilio, :edad, :email, :fecha_alta, :foto, :matricula, :motivo_consulta, :nombre, :sexo, :telefono
  validates_presence_of :Edo_Civil, :ciudad, :colonia, :domicilio, :edad, :email, :fecha_alta, :foto, :matricula, :motivo_consulta, :nombre, :sexo, :telefono
  validates_numericality_of :matricula
  FOTOS = File.join Rails.root, 'public', 'photo_store'

  after_save :guardar_foto



  def photo=(file_data)
    unless file_data.blank?
       @file_data = file_data
        self.extension = file_data.original_filename.split('.').last.downcase
    end

  end

  def photo_filename
    File.join FOTOS, "#{id}.#{extension}"
  end

  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  private


  def guardar_foto
    if @file_data
      FileUtils.mkdir_p FOTOS
      File.open(fhoto_filename, 'wb') do |f|
      f.write(@file_date.read)
      end
      @file_data  = nil

    end

  end

  validates_uniqueness_of :matricula
  validates_format_of :foto,
                      :with => %r{\.(gif|jpg|png|)$}i,
                      :message => 'must be a URL for GIF, JPG' +
                          'or PNG image.'
  protected
  def price_must_be_at_least_a_cent
    errors.add(:matricula, 'should be at least 3512120---' ) if matricula.nil? ||
        matricula < 3512120
  end



end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  # GET /contactos
  # GET /contactos.json
  def index
    @contactos = Contacto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contactos }
    end
  end

  # GET /contactos/1
  # GET /contactos/1.json
  def show
    @contacto = Contacto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contacto }
    end
  end

  # GET /contactos/new
  # GET /contactos/new.json
  def new
    @contacto = Contacto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contacto }
    end
  end

  # GET /contactos/1/edit
  def edit
    @contacto = Contacto.find(params[:id])
  end

  # POST /contactos
  # POST /contactos.json
  def create
    @contacto = Contacto.new(params[:contacto])

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to @contacto, notice: 'Contacto was successfully created.' }
        format.json { render json: @contacto, status: :created, location: @contacto }
      else
        format.html { render action: "new" }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contactos/1
  # PUT /contactos/1.json
  def update
    @contacto = Contacto.find(params[:id])

    respond_to do |format|
      if @contacto.update_attributes(params[:contacto])
        format.html { redirect_to @contacto, notice: 'Contacto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.json
  def destroy
    @contacto = Contacto.find(params[:id])
    @contacto.destroy

    respond_to do |format|
      format.html { redirect_to contactos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/contactos/_form.html.erb
<%= form_for(@contacto, html: {multipart: true}) do |f| %>
  <% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foto %><br />

    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br />
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.text_field :edad %>
  </div>
  <div class="field">
    <%= f.label :domicilio %><br />
    <%= f.text_field :domicilio %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br />
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br />
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :fecha_alta %><br />
    <%= f.date_select :fecha_alta %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :Edo_Civil %><br />
    <%= f.text_field :Edo_Civil %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :motivo_consulta %><br />
    <%= f.text_field :motivo_consulta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactos/edit.html.erb
<h1>Editing contacto</h1>

<%= render 'form' %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactos_path %>

app/views/contactos/index.html.erb
<h1>Lista de Contactos</h1>

<table>
  <tr>
    <th>Foto</th>
    <th>Matricula</th>
    <th>Nombre</th>
    <th>Sexo</th>
    <th>Edad</th>
    <th>Domicilio</th>
    <th>Colonia</th>
    <th>Ciudad</th>
    <th>Fecha alta</th>
    <th>Telefono</th>
    <th>Edo civil</th>
    <th>Email</th>
    <th>Motivo consulta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contactos.each do |contacto| %>
  <tr>
    <td><%= image_tag contacto.foto %></td>
    <td><%= contacto.matricula %></td>
    <td><%= contacto.nombre %></td>
    <td><%= contacto.sexo %></td>
    <td><%= contacto.edad %></td>
    <td><%= contacto.domicilio %></td>
    <td><%= contacto.colonia %></td>
    <td><%= contacto.ciudad %></td>
    <td><%= contacto.fecha_alta %></td>
    <td><%= contacto.telefono %></td>
    <td><%= contacto.Edo_Civil %></td>
    <td><%= contacto.email %></td>
    <td><%= contacto.motivo_consulta %></td>
    <td><%= link_to 'Show', contacto %></td>
    <td><%= link_to 'Edit', edit_contacto_path(contacto) %></td>
    <td><%= link_to 'Destroy', contacto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contacto', new_contacto_path %>

app/views/contactos/new.html.erb
<h1>New contacto</h1>

<%= render 'form' %>

<%= link_to 'Back', contactos_path %>

app/views/contactos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Foto:</b>
  <%= @contacto.foto %>
</p>

<p>
  <b>Matricula:</b>
  <%= @contacto.matricula %>
</p>

<p>
  <b>Nombre:</b>
  <%= @contacto.nombre %>
</p>

<p>
  <b>Sexo:</b>
  <%= @contacto.sexo %>
</p>

<p>
  <b>Edad:</b>
  <%= @contacto.edad %>
</p>

<p>
  <b>Domicilio:</b>
  <%= @contacto.domicilio %>
</p>

<p>
  <b>Colonia:</b>
  <%= @contacto.colonia %>
</p>

<p>
  <b>Ciudad:</b>
  <%= @contacto.ciudad %>
</p>

<p>
  <b>Fecha alta:</b>
  <%= @contacto.fecha_alta %>
</p>

<p>
  <b>Telefono:</b>
  <%= @contacto.telefono %>
</p>

<p>
  <b>Edo civil:</b>
  <%= @contacto.Edo_Civil %>
</p>

<p>
  <b>Email:</b>
  <%= @contacto.email %>
</p>

<p>
  <b>Motivo consulta:</b>
  <%= @contacto.motivo_consulta %>
</p>


<%= link_to 'Edit', edit_contacto_path(@contacto) %> |
<%= link_to 'Back', contactos_path %>