config/routes.rb
Agenda::Application.routes.draw do
  resources :sessions

  resources :datos_significativos

  resources :tratamiento_previos

  resources :cita

  resources :contactos

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

end

app/controllers/cita_controller.rb
class CitaController < ApplicationController
  # GET /cita
  # GET /cita.json
  def index
    @cita = Citum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cita }
    end
  end

  # GET /cita/1
  # GET /cita/1.json
  def show
    @citum = Citum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @citum }
    end
  end

  # GET /cita/new
  # GET /cita/new.json
  def new
    @citum = Citum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @citum }
    end
  end

  # GET /cita/1/edit
  def edit
    @citum = Citum.find(params[:id])
  end

  # POST /cita
  # POST /cita.json
  def create
    @citum = Citum.new(params[:citum])

    respond_to do |format|
      if @citum.save
        format.html { redirect_to @citum, notice: 'Citum was successfully created.' }
        format.json { render json: @citum, status: :created, location: @citum }
      else
        format.html { render action: "new" }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cita/1
  # PUT /cita/1.json
  def update
    @citum = Citum.find(params[:id])

    respond_to do |format|
      if @citum.update_attributes(params[:citum])
        format.html { redirect_to @citum, notice: 'Citum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cita/1
  # DELETE /cita/1.json
  def destroy
    @citum = Citum.find(params[:id])
    @citum.destroy

    respond_to do |format|
      format.html { redirect_to cita_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/views/cita/_form.html.erb
<%= form_for(@citum) do |f| %>
  <% if @citum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@citum.errors.count, "error") %> prohibited this citum from being saved:</h2>

      <ul>
      <% @citum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br />
    <%= f.number_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :tema %><br />
    <%= f.text_field :tema %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :hora_de_inicio %><br />
    <%= f.time_select :hora_de_inicio %>
  </div>
  <div class="field">
    <%= f.label :hora_fin %><br />
    <%= f.time_select :hora_fin %>
  </div>
  <div class="field">
    <%= f.label :resultado %><br />
    <%= f.text_field :resultado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cita/edit.html.erb
<h1>Editing citum</h1>

<%= render 'form' %>

<%= link_to 'Show', @citum %> |
<%= link_to 'Back', cita_path %>

app/views/cita/index.html.erb
<h1>Lista de las citas</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Tema</th>
    <th>Fecha</th>
    <th>Estado</th>
    <th>Hora de inicio</th>
    <th>Hora fin</th>
    <th>Resultado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cita.each do |citum| %>
  <tr>
    <td><%= citum.matricula %></td>
    <td><%= citum.tema %></td>
    <td><%= citum.fecha %></td>
    <td><%= citum.estado %></td>
    <td><%= citum.hora_de_inicio %></td>
    <td><%= citum.hora_fin %></td>
    <td><%= citum.resultado %></td>
    <td><%= link_to 'Show', citum %></td>
    <td><%= link_to 'Edit', edit_citum_path(citum) %></td>
    <td><%= link_to 'Destroy', citum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Citum', new_citum_path %>

app/views/cita/new.html.erb
<h1>New citum</h1>

<%= render 'form' %>

<%= link_to 'Back', cita_path %>

app/views/cita/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @citum.matricula %>
</p>

<p>
  <b>Tema:</b>
  <%= @citum.tema %>
</p>

<p>
  <b>Fecha:</b>
  <%= @citum.fecha %>
</p>

<p>
  <b>Estado:</b>
  <%= @citum.estado %>
</p>

<p>
  <b>Hora de inicio:</b>
  <%= @citum.hora_de_inicio %>
</p>

<p>
  <b>Hora fin:</b>
  <%= @citum.hora_fin %>
</p>

<p>
  <b>Resultado:</b>
  <%= @citum.resultado %>
</p>


<%= link_to 'Edit', edit_citum_path(@citum) %> |
<%= link_to 'Back', cita_path %>